"use client";
import {useState} from "react";
import {profile,skillGroups,projects,internships,certifications,certificateImages,education,type Project} from "../data/resumeData";

function Button({href,children,primary=false}:{href:string;children:React.ReactNode;primary?:boolean}){return <a className={primary?"btn primary":"btn"} href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined}>{children}</a>}
function ProjectCard({p,onOpen}:{p:Project;onOpen:(p:Project)=>void}){return <article className="card project" onClick={()=>onOpen(p)}><div className="projectTop"><span className="eyebrow">{p.category||"Project"}</span>{p.featured&&<span className="badge">Featured</span>}</div><h3>{p.title}</h3><p>{p.tagline}</p><div className="chips">{p.stack.slice(0,5).map(x=><span key={x}>{x}</span>)}</div><div className="projectFoot"><span>{p.period}</span><span>View details →</span></div></article>}
export default function Home(){
 const [active,setActive]=useState<Project|null>(null);
 return <main>
  <nav className="nav"><a className="brand" href="#top">nasrin.a</a><div className="navlinks">{[["About","about"],["Skills","skills"],["Projects","projects"],["Experience","experience"],["Certificates","certifications"],["Education","education"],["Contact","contact"]].map(([a,b])=><a key={b} href={'#'+b}>{a}</a>)}</div><a className="navcta" href={profile.resumeFile}>Resume</a></nav>
  <section id="top" className="hero wrap"><div><span className="route">● AVAILABLE FOR ENTRY-LEVEL ROLES</span><h1>Hi, I'm <span>Nasrin A</span></h1><h2>Python Developer & Software Engineer</h2><p className="lead">Backend development, REST APIs, ETL/data engineering, AI/ML and IoT — building practical, production-focused applications with Python.</p><div className="actions"><Button primary href={profile.resumeFile}>Download Resume</Button><Button href="#projects">View Projects</Button><Button href={profile.github}>GitHub</Button></div><div className="stats"><div><b>13+</b><small>Projects</small></div><div><b>6</b><small>Internships</small></div><div><b>8.58</b><small>CGPA</small></div><div><b>Python</b><small>Primary stack</small></div></div></div><div className="heroCard"><div className="avatar">NA</div><div className="terminal"><div>$ whoami</div><strong>nasrin_a</strong><div>$ focus</div><strong>backend · data · ai · iot</strong><div>$ status</div><strong className="green">open_to_work</strong></div></div></section>
  <section id="about" className="section wrap"><div className="sectionHead"><span className="route">GET /about</span><h2>About</h2></div><div className="aboutGrid"><div><p>{profile.summary}</p><p>Graduated in Electronics and Communication Engineering with hands-on software projects across Flask applications, data pipelines, AI/computer vision, embedded systems and IoT.</p></div><div className="aboutTags">{["Python","Backend Development","REST APIs","ETL / Data Engineering","AI / ML","IoT / Embedded","Git / GitHub","Problem Solving"].map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section id="skills" className="section soft"><div className="wrap"><div className="sectionHead"><span className="route">GET /skills</span><h2>Technical Skills</h2></div><div className="skillGrid">{skillGroups.map(g=><div className="card skill" key={g.label}><h3>{g.label}</h3><div className="chips">{g.items.map(x=><span key={x}>{x}</span>)}</div></div>)}</div></div></section>
  <section id="projects" className="section wrap"><div className="sectionHead"><span className="route">GET /projects</span><h2>Projects</h2><p>Featured engineering work, AI/ML projects, IoT/embedded work and the complete Oasis Infobyte project set.</p></div><div className="projectGrid">{projects.map(p=><ProjectCard key={p.slug} p={p} onOpen={setActive}/>)}</div></section>
  <section id="experience" className="section soft"><div className="wrap"><div className="sectionHead"><span className="route">GET /experience</span><h2>Internships</h2></div><div className="timeline">{internships.map(j=><div className="timelineItem" key={j.company}><div className={'dot '+(j.current?'current':'')}></div><div className="card job"><div className="jobHead"><div><h3>{j.role}</h3><b>{j.company}</b></div><span className="period">{j.period}</span>{j.current&&<span className="currentTag">Present</span>}</div><ul>{j.bullets.map(b=><li key={b}>{b}</li>)}</ul></div></div>)}</div></div></section>
  <section id="iot" className="section wrap"><div className="sectionHead"><span className="route">GET /iot</span><h2>IoT & Embedded</h2><p>Wearable safety-band project developed around health monitoring, fall detection and emergency alerts.</p></div><div className="iotGrid"><div className="card iotText"><h3>IoT-Based Wearable Safety Band for Women and Elderly Patients</h3><p>ESP32-based wearable prototype using MAX30100, MPU6050 and OLED display, with a mobile-app interface and conference presentation.</p><div className="chips">{["ESP32","MAX30100","MPU6050","OLED","IoT","Embedded Systems","Health Monitoring","Fall Detection","SOS Alerts"].map(x=><span key={x}>{x}</span>)}</div></div><div className="gallery">{["/assets/images/1000257190.jpg","/assets/images/1000257188.jpg","/assets/images/1000257186.jpg","/assets/images/1000257192.jpg"].map(x=><img key={x} src={x} alt="IoT wearable project" />)}</div></div></section>
  <section id="certifications" className="section soft"><div className="wrap"><div className="sectionHead"><span className="route">GET /certifications</span><h2>Certifications, Training & Achievements</h2></div><div className="certGrid">{certifications.map(c=><div className="card cert" key={c[0]}><span className="certIcon">✓</span><h3>{c[0]}</h3><b>{c[1]}</b><small>{c[2]}</small></div>)}</div><h3 className="subhead">Certificate Gallery</h3><div className="certGallery">{certificateImages.map(x=><img key={x} src={x} alt="Nasrin certificate" />)}</div></div></section>
  <section id="education" className="section wrap"><div className="sectionHead"><span className="route">GET /education</span><h2>Education</h2></div><div className="eduGrid">{education.map(e=><div className="card edu" key={e[0]}><span className="eyebrow">{e[0]}</span><h3>{e[1]}</h3><p>{e[2]}</p><small>{e[3]}</small></div>)}</div></section>
  <section id="leetcode" className="section soft"><div className="wrap leet"><div><span className="route">GET /leetcode</span><h2>LeetCode</h2><p>Problem-solving practice and DSA preparation.</p></div><Button href={profile.leetcode}>View LeetCode Profile ↗</Button></div></section>
  <section id="contact" className="section wrap contact"><div className="sectionHead"><span className="route">POST /contact</span><h2>Let's build something</h2><p>Open to entry-level Python Developer, Software Developer, Backend, Data Engineering and AI/ML opportunities.</p></div><div className="contactLinks"><Button primary href={'mailto:'+profile.email}>Email Me</Button><Button href={profile.linkedin}>LinkedIn</Button><Button href={profile.github}>GitHub</Button><Button href={profile.leetcode}>LeetCode</Button></div><p className="email">{profile.email}</p></section>
  <footer>© 2026 Nasrin A · Python Developer & Software Engineer</footer>
  {active&&<div className="modalBackdrop" onClick={()=>setActive(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button><span className="route">GET /projects/{active.slug}</span><h2>{active.title}</h2><p>{active.overview}</p><h4>Features</h4><ul>{active.features.map(x=><li key={x}>{x}</li>)}</ul><h4>Tech Stack</h4><div className="chips">{active.stack.map(x=><span key={x}>{x}</span>)}</div>{active.images&&<div className="modalGallery">{active.images.map(x=><img key={x} src={x} alt={active.title}/>)}</div>}{active.videos&&<div className="videoGrid">{active.videos.map(x=><video key={x} controls src={x}/>)}</div>}<div className="modalActions">{active.github&&<Button primary href={active.github}>GitHub</Button>}{active.linkedin&&<Button href={active.linkedin}>LinkedIn Demo</Button>}{active.demo&&<Button href={active.demo}>Live Demo</Button>}</div></div></div>}
 </main>
}
